"""
Generates a true AcroForm-interactive fillable PDF using ReportLab's canvas.acroForm API.
Fields are real PDF form widgets — clickable and fillable in any PDF viewer.
'list' type renders ADD_ROWS_COUNT pre-labelled rows so the customer can fill multiple entries.
"""
import os
from datetime import date as _date
from reportlab.lib.pagesizes import LETTER
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

# ── Layout constants ────────────────────────────────────────────────────────
MARGIN_X        = 0.70 * inch
MARGIN_Y_BOTTOM = 0.65 * inch
PAGE_W, PAGE_H  = LETTER

LABEL_FONT      = "Helvetica-Bold"
HINT_FONT       = "Helvetica-Oblique"
BODY_FONT       = "Helvetica"
LABEL_SIZE      = 8.5
BODY_SIZE       = 9

# Field dimensions
TEXT_H          = 0.26 * inch
TEXTAREA_H      = 0.72 * inch
CB_SIZE         = 0.15 * inch
FIELD_W         = PAGE_W - MARGIN_X * 2   # full width by default
GAP_AFTER_FIELD = 0.18 * inch             # space between bottom of field and next label
GAP_LABEL       = 0.14 * inch             # space between label and top of field
ROW_LABEL_GAP   = 0.08 * inch

# For 'list' fields — how many blank rows to pre-render
ADD_ROWS_COUNT  = 3

# Colours
COL_HEADER_BG   = colors.HexColor("#1C1C2E")   # deep midnight
COL_HEADER_TEXT = colors.white
COL_LABEL       = colors.HexColor("#3D2C00")   # deep earth brown
COL_REQUIRED    = colors.HexColor("#C0392B")
COL_FIELD_BG    = colors.HexColor("#FFFDF7")   # warm ivory
COL_FIELD_BORD  = colors.HexColor("#C9A84C")   # Kente gold border
COL_DIVIDER     = colors.HexColor("#E8D9B0")
COL_FOOTER      = colors.HexColor("#7A6030")
COL_PAGE_BG     = colors.HexColor("#FDFAF3")   # warm off-white page


# ── Internal helpers ────────────────────────────────────────────────────────

def _start_page(c: canvas.Canvas, title: str):
    """Paint background and header on a new page."""
    # Page background
    c.setFillColor(COL_PAGE_BG)
    c.rect(0, 0, PAGE_W, PAGE_H, fill=1, stroke=0)

    # Header band
    c.setFillColor(COL_HEADER_BG)
    c.rect(0, PAGE_H - 1.05 * inch, PAGE_W, 1.05 * inch, fill=1, stroke=0)

    # Gold accent line below header
    c.setStrokeColor(colors.HexColor("#C9A84C"))
    c.setLineWidth(2.5)
    c.line(0, PAGE_H - 1.05 * inch, PAGE_W, PAGE_H - 1.05 * inch)

    # Title
    c.setFillColor(COL_HEADER_TEXT)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(MARGIN_X, PAGE_H - 0.58 * inch, title)

    c.setFillColor(colors.HexColor("#C9A84C"))
    c.setFont("Helvetica", 8)
    c.drawString(MARGIN_X, PAGE_H - 0.82 * inch,
                 "Complete all required fields (*) and return to your insurance agent.")

    # "Generated by Herve" — right-aligned in header
    c.setFillColor(colors.HexColor("#E8D9B0"))
    c.setFont("Helvetica-Oblique", 7.5)
    c.drawRightString(PAGE_W - MARGIN_X, PAGE_H - 0.60 * inch, "Generated by Herve")
    c.setFont("Helvetica", 7)
    c.drawRightString(PAGE_W - MARGIN_X, PAGE_H - 0.80 * inch, "WebToForm · AI Insurance Tools")


def _draw_footer(c: canvas.Canvas, page_num: int, total_pages: int):
    c.setStrokeColor(COL_DIVIDER)
    c.setLineWidth(0.5)
    c.line(MARGIN_X, MARGIN_Y_BOTTOM - 0.08 * inch,
           PAGE_W - MARGIN_X, MARGIN_Y_BOTTOM - 0.08 * inch)
    c.setFillColor(COL_FOOTER)
    c.setFont(BODY_FONT, 7.5)
    c.drawString(MARGIN_X, MARGIN_Y_BOTTOM - 0.25 * inch,
                 "CONFIDENTIAL — Insurance Customer Information Form")
    c.drawRightString(PAGE_W - MARGIN_X, MARGIN_Y_BOTTOM - 0.25 * inch,
                      f"Page {page_num}")


def _safe_field_name(label: str, index: int) -> str:
    """Produce a unique, AcroForm-safe field name."""
    safe = "".join(c if c.isalnum() else "_" for c in label)
    return f"field_{index}_{safe}"[:64]


def _draw_label(c: canvas.Canvas, x: float, y: float, label: str, required: bool):
    c.setFillColor(COL_LABEL)
    c.setFont(LABEL_FONT, LABEL_SIZE)
    display = label + (" *" if required else "")
    c.drawString(x, y, display)


# ── Page manager ────────────────────────────────────────────────────────────

class PageManager:
    """Tracks current y-position, creates new pages automatically."""

    def __init__(self, c: canvas.Canvas, title: str):
        self.c = c
        self.title = title
        self.page_num = 0
        self._new_page()

    def _new_page(self):
        if self.page_num > 0:
            self.c.showPage()
        self.page_num += 1
        _start_page(self.c, self.title)
        self.y = PAGE_H - 1.25 * inch   # first field starts here

    def ensure(self, needed: float):
        """Ensure `needed` vertical space is available; break page if not."""
        if self.y - needed < MARGIN_Y_BOTTOM:
            self._new_page()

    def finish(self):
        _draw_footer(self.c, self.page_num, self.page_num)
        # Patch all previous pages — we don't know total until the end,
        # so footer text just shows the current page number (kept simple).


# ── Field renderers ─────────────────────────────────────────────────────────

def _render_text(pm: PageManager, label: str, required: bool,
                 field_name: str, multiline: bool = False, default_value: str = ""):
    fh = TEXTAREA_H if multiline else TEXT_H
    needed = GAP_LABEL + fh + GAP_AFTER_FIELD + LABEL_SIZE / 72 * inch
    pm.ensure(needed)

    label_y = pm.y - LABEL_SIZE / 72 * inch
    _draw_label(pm.c, MARGIN_X, label_y, label, required)

    field_y = label_y - GAP_LABEL - fh
    kwargs = dict(
        name=field_name,
        tooltip=label,
        x=MARGIN_X, y=field_y,
        width=FIELD_W, height=fh,
        borderColor=COL_FIELD_BORD,
        fillColor=COL_FIELD_BG,
        textColor=colors.HexColor("#1C1C2E"),
        borderWidth=1,
        fontSize=BODY_SIZE,
        fontName=BODY_FONT,
    )
    if multiline:
        kwargs["fieldFlags"] = "multiline"
    if default_value:
        kwargs["value"] = default_value
    pm.c.acroForm.textfield(**kwargs)
    pm.y = field_y - GAP_AFTER_FIELD


def _render_checkbox(pm: PageManager, label: str, required: bool, field_name: str):
    needed = CB_SIZE + GAP_AFTER_FIELD + 0.05 * inch
    pm.ensure(needed)

    cb_y = pm.y - CB_SIZE
    pm.c.acroForm.checkbox(
        name=field_name,
        tooltip=label,
        x=MARGIN_X, y=cb_y,
        size=CB_SIZE * (72 / inch),   # points
        borderColor=COL_FIELD_BORD,
        fillColor=COL_FIELD_BG,
        borderWidth=1,
        checked=False,
    )
    # Label beside the checkbox
    pm.c.setFillColor(COL_LABEL)
    pm.c.setFont(BODY_FONT, BODY_SIZE)
    suffix = " *" if required else ""
    pm.c.drawString(MARGIN_X + CB_SIZE + 0.1 * inch,
                    cb_y + CB_SIZE * 0.25,
                    label + suffix)
    pm.y = cb_y - GAP_AFTER_FIELD


def _render_list(pm: PageManager, label: str, required: bool,
                 field_name: str, row_count: int = ADD_ROWS_COUNT):
    """Render a repeating list: a section header + N numbered text-field rows."""
    # Section sub-header
    needed = (LABEL_SIZE / 72 * inch) + row_count * (TEXT_H + ROW_LABEL_GAP + GAP_AFTER_FIELD * 0.6) + 0.1 * inch
    pm.ensure(min(needed, (PAGE_H - 1.3 * inch - MARGIN_Y_BOTTOM) * 0.85))

    label_y = pm.y - LABEL_SIZE / 72 * inch
    _draw_label(pm.c, MARGIN_X, label_y, label + (" *" if required else ""), False)

    # Gold underline for the section header
    pm.c.setStrokeColor(colors.HexColor("#C9A84C"))
    pm.c.setLineWidth(0.75)
    pm.c.line(MARGIN_X, label_y - 2, PAGE_W - MARGIN_X, label_y - 2)

    pm.y = label_y - GAP_LABEL * 1.2
    row_w = FIELD_W

    for i in range(1, row_count + 1):
        needed_row = TEXT_H + ROW_LABEL_GAP + GAP_AFTER_FIELD * 0.5
        pm.ensure(needed_row)

        # Row number label
        row_label_y = pm.y - LABEL_SIZE / 72 * inch * 0.85
        pm.c.setFillColor(colors.HexColor("#8B6914"))
        pm.c.setFont(HINT_FONT, 7.5)
        pm.c.drawString(MARGIN_X, row_label_y, f"#{i}")

        field_y = row_label_y - ROW_LABEL_GAP - TEXT_H
        row_name = f"{field_name}_row{i}"
        pm.c.acroForm.textfield(
            name=row_name,
            tooltip=f"{label} #{i}",
            x=MARGIN_X + 0.22 * inch, y=field_y,
            width=row_w - 0.22 * inch, height=TEXT_H,
            borderColor=COL_FIELD_BORD,
            fillColor=COL_FIELD_BG,
            textColor=colors.HexColor("#1C1C2E"),
            borderWidth=0.75,
            fontSize=BODY_SIZE,
            fontName=BODY_FONT,
        )
        pm.y = field_y - GAP_AFTER_FIELD * 0.6

    # "Additional details" textarea below the rows
    details_label_y = pm.y - LABEL_SIZE / 72 * inch * 0.9
    pm.c.setFillColor(colors.HexColor("#8B6914"))
    pm.c.setFont(HINT_FONT, 7.5)
    pm.c.drawString(MARGIN_X, details_label_y, "Additional details (optional)")
    pm.ensure(TEXTAREA_H + GAP_LABEL + GAP_AFTER_FIELD)
    field_y = details_label_y - GAP_LABEL - TEXTAREA_H
    pm.c.acroForm.textfield(
        name=f"{field_name}_details",
        tooltip=f"{field_name} — additional details",
        x=MARGIN_X, y=field_y,
        width=FIELD_W, height=TEXTAREA_H,
        borderColor=COL_FIELD_BORD,
        fillColor=COL_FIELD_BG,
        textColor=colors.HexColor("#1C1C2E"),
        borderWidth=0.75,
        fontSize=BODY_SIZE,
        fontName=BODY_FONT,
        fieldFlags="multiline",
    )
    pm.y = field_y - GAP_AFTER_FIELD * 1.2


# ── Public API ──────────────────────────────────────────────────────────────

def create_fillable_pdf(fields: list[dict], output_path: str,
                        title: str = "Customer Information Form"):
    """
    Build a true AcroForm fillable PDF from a list of field descriptors.

    Field dict keys:
      label    : str
      type     : text | textarea | date | email | phone | checkbox | list
      required : bool
    """
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

    c = canvas.Canvas(output_path, pagesize=LETTER)
    c.setTitle(title)
    c.setAuthor("WebToForm — AI Insurance Form Generator")

    pm = PageManager(c, title)

    today_str = _date.today().strftime("%m / %d / %Y")

    hint_map = {
        "date":  f" (MM / DD / YYYY)",
        "email": " (email address)",
        "phone": " (phone number)",
    }

    for idx, field in enumerate(fields):
        label    = str(field.get("label", "Field")).strip()
        ftype    = field.get("type", "text")
        required = bool(field.get("required", False))
        fname    = _safe_field_name(label, idx)
        display  = label + hint_map.get(ftype, "")

        if ftype == "checkbox":
            _render_checkbox(pm, display, required, fname)
        elif ftype == "textarea":
            _render_text(pm, display, required, fname, multiline=True)
        elif ftype == "list":
            _render_list(pm, display, required, fname)
        elif ftype == "date":
            _render_text(pm, display, required, fname, multiline=False,
                         default_value=today_str)
        else:
            # text, email, phone all use a single-line textfield
            _render_text(pm, display, required, fname, multiline=False)

    # Required field legend
    pm.ensure(0.35 * inch)
    pm.c.setFillColor(COL_REQUIRED)
    pm.c.setFont(BODY_FONT, 7.5)
    pm.c.drawString(MARGIN_X, pm.y - 0.18 * inch, "* Required field")

    pm.finish()
    c.save()
